defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/python:3.10-node

version: 4
jobs:
  verify:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Making report folder
          command: /bin/mkdir -p /tmp/PSO2es
      - run:
          name: Checking for vaild JSONs
          command: ./_py/checkjson.py | /usr/bin/tee /tmp/PSO2es/checkjson.txt
      - store_artifacts:
          path: /tmp/PSO2es/
          destination: Reports

  tests:
    <<: *defaults
    steps:
      - run:
          name: Making report folder
          command: /bin/mkdir -p /tmp/PSO2es
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - run:
          name: Checking translation progress
          command: /bin/sh ./_sh/coverage.sh | /usr/bin/tee /tmp/PSO2es/coverage.txt
      - run:
          name: Checking for existing item mappings
          command: ./_py/dupcheck.py | /usr/bin/tee /tmp/PSO2es/dupcheck.txt
      - run:
          name: Checking for duplicate entries
          command: ./_py/dupassign.py | /usr/bin/tee /tmp/PSO2es/dupassign.txt
      - run:
          name: Checking if Dice Chat has too many lines
          command: ./_py/DiceLen.py | /usr/bin/tee /tmp/PSO2es/DiceLen.txt
      - run:
          name: Checking if title names are too long
          command: ./_py/TitleLen.py | /usr/bin/tee /tmp/PSO2es/TitleLen.txt
      - run:
          name: Checking if block names are too long
          command: ./_py/BlockLen.py | /usr/bin/tee /tmp/PSO2es/BlockLen.txt
      - run:
          name: Checking if JSON files are tidy
          command: ./_py/tidy-json.py
      - run:
          name: Tidy changes
          command: /usr/bin/git diff --exit-code | /usr/bin/tee /tmp/PSO2es/tidy.diff
          when: on_fail
      - run:
          name: Applying Tidy changes
          command: /usr/bin/git add -u
          when: on_fail
      - store_artifacts:
          path: /tmp/PSO2es/
          destination: Reports
          
  font_big:
    <<: *defaults
    steps:
      - run:
          name: Making report folder
          command: /bin/mkdir -p /tmp/PSO2es
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - restore_cache:
          key: pip1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python packages
          command: pip install -r requirements.txt
      - save_cache:
          key: pip1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - run:
          name: Word wrap changes for long item descriptions
          command: /usr/bin/git diff --exit-code | /usr/bin/tee /tmp/PSO2es/ItemDescFont.diff
          when: on_fail
      - run:
          name: Applying changes
          command: /usr/bin/git add -u
          when: on_fail
      - store_artifacts:
          path: /tmp/PSO2es/
          destination: Reports

  build:
    working_directory: ~/repo
    docker:
      - image: mono:latest
    steps:
      - run:
          name: Update APT listing
          command: apt-get -qq update
      - run:
          name: Install git, wget, unzip, zip and ssh
          command: apt-get -qq -y --no-install-recommends install git wget unzip zip openssh-client
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - restore_cache:
          keys:
            # Find the most recent cache used from any branch
            - v1-APK-
      - run:
          name: Download APKs files
          command: /bin/bash ./.circleci/prebuild.sh .
      - run:
          name: Move required DLLs
          command: /bin/mv -v lib/ContentsSerializer.dll lib/Assembly-CSharp-firstpass.dll lib/UnityEngine.dll lib/protobuf-net.dll lib/ProtoBuffSerializer.dll .
      - run:
          name: Remove extra DLLs
          command: /bin/rm -v lib/*.dll
      - run:
          name: Link PSO2 APK for caching
          command: /bin/ln -s -v lib/*.apk PSO2es.apk
      - save_cache:
          key: v1-APK-{{ checksum "PSO2es.apk" }}
          paths:
            - lib/
      - restore_cache:
          keys:
            - v1-Databases-
      - run:
          name: Download JP Context
          command: /usr/bin/wget "http://pso2es.10nub.es/patchJP.zip" --no-http-keep-alive --dns-timeout=15 --read-timeout=30 --timestamping
      - run:
          name: Unpack JP Context
          command: /usr/bin/unzip -xuoq patchJP.zip -d Databases
      - save_cache:
          key: v1-Databases-{{ checksum "patchJP.zip" }}
          paths:
            - patchJP.zip
      - restore_cache:
          keys:
            - v1-esbreaker-
      - run:
          name: Download ESBreaker
          command: /usr/bin/wget "http://pso2es.10nub.es/esbreaker.zip" --no-http-keep-alive --dns-timeout=15 --read-timeout=30 --timestamping
      - run:
          name: Unpack ESBreaker
          command: /usr/bin/unzip -xuoq esbreaker.zip
      - save_cache:
          key: v1-esbreaker-{{ checksum "esbreaker.zip" }}
          paths:
            - esbreaker.zip
      - run:
          name: Get GIT version
          command: /usr/bin/git describe --always --tags | /usr/bin/tee /tmp/patchBeta.txt
      - run:
          name: Making report folder
          command: mkdir -p /tmp/PSO2es
      - run:
          name: Run ESBreaker
          command: /usr/bin/mono ESBreakerCLI.exe | /usr/bin/tee /tmp/PSO2es/ESBreaker.txt
      - run:
          name: Packing Patch
          command: cd output/ && /usr/bin/zip -r /tmp/patchBeta.zip .
      - run:
          name: Leftover changes
          command: /usr/bin/git diff --exit-code | /usr/bin/tee /tmp/PSO2es/ESBreaker.diff
      - store_artifacts:
          path: /tmp/patchBeta.zip
          destination: patchBeta.zip
      - store_artifacts:
          path: /tmp/patchBeta.txt
          destination: patchBeta.txt
      - store_artifacts:
          path: /tmp/PSO2es/
          destination: Reports

workflows:
  version: 2
  verify-test&build:
    jobs:
      - verify
      - font_big:
          requires:
            - verify
      - tests:
          requires:
            - verify
