name: repo-check
on: [push]
jobs:
   test:
      runs-on: ubuntu-latest
      container: cimg/python:3.10-node
          
      steps:
        - name: Setting up Python 3.8
          with:
            python-version: '3.8'
            architecture: 'x64'
          
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
          
        - name: Setting up testing environment
          run: sudo chmod -R 777 $GITHUB_WORKSPACE /tmp/PSO2es
          
        - uses: actions/checkout@v3
          
        - name: Checking for vaild JSONs
          run: ./_py/checkjson.py | /usr/bin/tee /tmp/PSO2es/checkjson.txt
          
        - name: Store artifacts
          uses: actions/upload-artifact@v3
          with:
            path: /tmp/PSO2es/
